{{- if .Values.aiGateway.enabled }}
{{- if .Values.aiGateway.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: ai-gateway-secrets
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
type: Opaque
data:
  dbUrl: {{ .Values.aiGateway.secrets.dbUrl | toString | b64enc }}
  dbCert: {{ .Values.aiGateway.secrets.dbCert | toString | b64enc }}
  aiGwS3AccessKey: {{ .Values.aiGateway.secrets.aiGwS3AccessKey | toString | b64enc }}
  aiGwS3SecretKey: {{ .Values.aiGateway.secrets.aiGwS3SecretKey | toString | b64enc }}
{{- end }}
{{- end }}