{{- if .Values.aiGateway.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ai-gateway-secrets
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
type: Opaque
data:
  dbUrl: {{ .Values.aiGateway.secrets.dbUrl | toString | b64enc }}
  dbCert: {{ .Values.aiGateway.secrets.dbCert | toString | b64enc }}
{{- end }}