{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ai-gateway-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    {{- include "helicone.annotations" . | nindent 4 }}
type: Opaque
data:
  {{- $secrets := .Values.aiGateway.secrets | default dict }}
  dbUrl: {{ $secrets.dbUrl | default "" | toString | b64enc }}
  dbCert: {{ $secrets.dbCert | default "" | toString | b64enc }}
  aiGwS3AccessKey: {{ $secrets.aiGwS3AccessKey | default "" | toString | b64enc }}
  aiGwS3SecretKey: {{ $secrets.aiGwS3SecretKey | default "" | toString | b64enc }}
{{- end }}