{{- if .Values.aiGateway.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helicone.ai-gateway.name" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.aiGateway.serviceAccount.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.aiGateway.serviceAccount.roleArn | quote }}
    {{- end }}
    {{- with .Values.aiGateway.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }} 