{{- if .Values.aiGateway.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helicone.ai-gateway.serviceAccountName" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
    aws.amazon.com/pod-identity: "enabled"
  annotations:
    {{- with .Values.aiGateway.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }} 