{{- if .Values.externalSecrets.enabled | default false }}
{{- if .Values.helicone.clickhouse.enabled }}
# Internal ClickHouse secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: helicone-clickhouse-sync
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "30s" | quote }}
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.helicone.config.clickhouseSecretsName | default (printf "%s-secrets" (include "clickhouse.name" .)) | quote }}
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix | default "helicone" }}/clickhouse
        property: user
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix | default "helicone" }}/clickhouse
        property: password
{{- else }}
# External ClickHouse secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: helicone-external-clickhouse-sync
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "30s" | quote }}
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.helicone.config.externalClickhouseSecretName | quote }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.helicone.config.externalClickhouseUsernameKey | quote }}
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix | default "helicone" }}/external-clickhouse
        property: username
    - secretKey: {{ .Values.helicone.config.externalClickhousePasswordKey | quote }}
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix | default "helicone" }}/external-clickhouse
        property: password
{{- end }}
{{- end }} 