{{- if .Values.externalSecrets.enabled | default false }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.aws.region | default "us-west-2" | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: "external-secrets"  # ESO service account in bootstrap namespace
            namespace: "bootstrap"
{{- end }}