{{- if .Values.externalSecrets.enabled | default false }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.externalSecrets.serviceAccount.name | default "external-secrets-sa" | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    {{- include "helicone.annotations" . | nindent 4 }}
    argocd.argoproj.io/sync-wave: "-2"
    {{- if .Values.externalSecrets.serviceAccount.annotations }}
    {{- toYaml .Values.externalSecrets.serviceAccount.annotations | nindent 4 }}
    {{- end }}
{{- end }}