{{- if .Values.helicone.aiGateway.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: helicone-ai-gateway-secrets
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
type: Opaque
data:
  helicone_api_key: {{ .Values.helicone.aiGateway.secrets.heliconeApiKey | default "HELICONE_API_KEY" | toString | b64enc }}
  openai_api_key: {{ .Values.helicone.aiGateway.secrets.openaiApiKey | default "OPENAI_API_KEY" | toString | b64enc }}
  anthropic_api_key: {{ .Values.helicone.aiGateway.secrets.anthropicApiKey | default "ANTHROPIC_API_KEY" | toString | b64enc }}
  gemini_api_key: {{ .Values.helicone.aiGateway.secrets.geminiApiKey | default "GEMINI_API_KEY" | toString | b64enc }}
{{- end }}