{{- if .Values.helicone.aiGateway.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: helicone-ai-gateway-secrets
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
type: Opaque
data:
  db-url: {{ .Values.helicone.aiGateway.secrets.dbUrl | toString | b64enc }}
  db-cert: {{ .Values.helicone.aiGateway.secrets.dbCert | toString | b64enc }}
{{- end }}