{{- if .Values.helicone.aiGateway.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: helicone-ai-gateway-secrets
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
type: Opaque
data:
  db_url: {{ .Values.helicone.aiGateway.secrets.dbUrl | default "postgres://" | toString | b64enc }}
{{- end }}