aiGateway:
  enabled: true
  image:
    repository: helicone/ai-gateway
    pullPolicy: IfNotPresent
    #tag: "sha-90af8c4"
    tag: "sha-72280bd"
  replicaCount: 2

  # EKS Pod Identity Service Account Configuration
  serviceAccount:
    enabled: true
    # Name of the service account (defaults to chart name if not specified)
    name: "helicone-ai-gateway"
    # IAM role ARN for EKS Pod Identity
    # This should be set to the IAM role that has permissions to access ElastiCache
    roleArn: "arn:aws:iam::849596434884:role/helicone-valkey-cache-pod-identity-role"
    # Additional annotations for the service account
    annotations: {}

  # Pod annotations (useful for pod identity debugging)
  podAnnotations: {}

  # # Valkey/ElastiCache configuration for dynamic connection
  # valkey:
  #   # Set these values to use dynamic configuration instead of hardcoded URLs
  #   # When endpoint is provided, it overrides the hardcoded config values
  #   endpoint: "" # e.g., "helicone-valkey-cache-hmjlk9.serverless.usw2.cache.amazonaws.com"
  #   port: 6379
  #   tls: true # Set to true for ElastiCache serverless which uses TLS

  # TODO: add canaries or blue-green
  # Rolling Update Deployment Strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

  # Progress deadline for deployments (in seconds)
  progressDeadlineSeconds: 90

  service:
    annotations: {}
    type: NodePort # Works with Gateway API ALB
    port: 8080

  # Gateway API configuration
  gateway:
    enabled: true # Gateway API for ALB
    className: "amazon-vpc-lattice" # AWS Gateway Controller class for ALB
    annotations:
      # AWS Gateway Controller annotations
      application-networking.k8s.aws/lattice-vpc-association: "default"
      # Load balancer configuration
      application-networking.k8s.aws/load-balancer-type: "application"
      application-networking.k8s.aws/scheme: "internal"
      # Health check configuration
      application-networking.k8s.aws/healthcheck-path: "/health"
      application-networking.k8s.aws/healthcheck-protocol: "HTTP"
      application-networking.k8s.aws/healthcheck-interval-seconds: "15"
      application-networking.k8s.aws/healthcheck-timeout-seconds: "5"
      application-networking.k8s.aws/healthy-threshold-count: "2"
      application-networking.k8s.aws/unhealthy-threshold-count: "5"
      # Connection settings for LLM streaming
      application-networking.k8s.aws/idle-timeout-seconds: "300"
      application-networking.k8s.aws/http2-enabled: "true"
      # Target group settings
      application-networking.k8s.aws/deregistration-delay-seconds: "20"
      # Tags
      application-networking.k8s.aws/tags: "Environment=production,Purpose=GlobalAccelerator"
    tls:
      enabled: true
      certificateRefs:
        - name: helicone-ai-tls-cert
          group: ""
          kind: Secret
    allowedRoutes:
      namespaces:
        from: Same # Same, All, or Selector
        # selector:  # Optional: label selector for allowed namespaces
        #   matchLabels:
        #     gateway-access: "true"
    addresses: [] # Optional: specify static IPs or DNS names
    httpRoute:
      hostnames:
        - "ai-gateway.helicone.ai"
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - name: ai-gateway
              port: 8080

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi

  # Health Probes Configuration
  livenessProbe:
    enabled: true
    httpGet:
      path: /health
      port: http
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    enabled: true
    httpGet:
      path: /health
      port: http
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1

  startupProbe:
    enabled: true
    httpGet:
      path: /health
      port: http
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 20
    successThreshold: 1

  config:
    telemetry:
      level: "info,ai_gateway=trace"
      format: "compact"
      exporter: both
      otlp-endpoint: "http://otel-collector.helicone-infrastructure.svc.cluster.local:4317/v1/metrics"

    helicone:
      features: all

    minio:
      bucket-name: "request-response-storage"
      region: "us-west-2"
      host: "https://s3.us-west-2.amazonaws.com"

    cache-store:
      type: redis
      host-url: "rediss://helicone-valkey-cache-hmjlk9.serverless.usw2.cache.amazonaws.com:6379"

    rate-limit-store:
      type: redis
      host-url: "rediss://helicone-valkey-cache-hmjlk9.serverless.usw2.cache.amazonaws.com:6379"

    deployment-target:
      type: cloud
