{{- if and .Values.helicone.s3 .Values.helicone.s3.serviceAccount .Values.helicone.s3.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jawn.name" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    {{- include "helicone.annotations" . | nindent 4 }}
    eks.amazonaws.com/role-arn: {{ .Values.helicone.s3.serviceAccount.roleArn | quote }}
{{- end }} 