helicone:
  aiGateway:
    enabled: true
    image:
      repository: helicone/ai-gateway
      pullPolicy: IfNotPresent
      tag: "sha-90af8c4"
    replicaCount: 2

    # TODO: add canaries or blue-green
    # Rolling Update Deployment Strategy
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%

    # Progress deadline for deployments (in seconds)
    progressDeadlineSeconds: 90

    service:
      annotations: {}
      type: ClusterIP
      port: 8080
    ingress:
      enabled: false
      className: "nginx"
      annotations: {}
      hosts:
        - host: helicone.ai/ai-gateway
          paths:
            - path: /
              pathType: Prefix
      tls: []
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 512Mi

    # Health Probes Configuration
    livenessProbe:
      enabled: true
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1

    readinessProbe:
      enabled: true
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 3
      failureThreshold: 3
      successThreshold: 1

    startupProbe:
      enabled: true
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 20
      successThreshold: 1

    config:
      telemetry:
        level: "info,ai_gateway=trace"
        format: "compact"
        exporter: stdout

      helicone:
        features: all

      minio:
        bucket-name: "request-response-storage"

      cache-store:
        type: redis

      rate-limit-store:
        type: redis

      deployment-target: cloud
