helicone:
  aiGateway:
    enabled: true
    image:
      repository: helicone/ai-gateway
      pullPolicy: IfNotPresent
      tag: "sha-765b2b1"
    replicaCount: 2
    
    # Region where this AI Gateway instance is deployed
    # This should match one of the regions configured in memorydb.multiRegion.regions
    region: "us-east-1"

    # Rolling Update Deployment Strategy
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%

    # Progress deadline for deployments (in seconds)
    progressDeadlineSeconds: 600

    service:
      annotations: {}
      type: ClusterIP
      port: 8080
    ingress:
      enabled: false
      className: "nginx"
      annotations: {}
      hosts:
        - host: helicone.ai/ai-gateway
          paths:
            - path: /
              pathType: Prefix
      tls: []
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 512Mi

    # Health Probes Configuration
    livenessProbe:
      enabled: true
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1

    readinessProbe:
      enabled: true
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
      successThreshold: 1

    startupProbe:
      enabled: true
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1

    extraEnvVars:
      - name: AI_GATEWAY__SERVER__ADDRESS
        value: "0.0.0.0"
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            name: helicone-ai-gateway-secrets
            key: openai_api_key
      # Only required if deployment target == cloud
      # - name: AI_GATEWAY__MINIO__ACCESS_KEY
      #   valueFrom:
      #     secretKeyRef:
      #       name: helicone-minio-secrets
      #       key: root_user
      # - name: AI_GATEWAY__MINIO__SECRET_KEY
      #   valueFrom:
      #     secretKeyRef:
      #       name: helicone-minio-secrets
      #       key: root_password
    config:
      routers:
        default:
          load-balance:
            chat:
              strategy: latency
              targets:
                - openai
                - anthropic
      providers:
        ollama:
          base-url: "http://ollama:11434"
        bedrock:
          base-url: "https://bedrock.us-east-1.amazonaws.com"
      helicone:
        authentication: true

  # AWS MemoryDB Configuration (Crossplane)
  memorydb:
    enabled: false

    # Global defaults (can be overridden per region)
    nodeType: db.r7g.large
    numShards: 1
    numReplicasPerShard: 1
    tlsEnabled: true

    # Optional: ACL name for authentication
    # aclName: "default"

    # Optional: Create a new parameter group
    createParameterGroup: false
    parameterGroupFamily: memorydb_valkey8
    parameters:
      []
      # - name: maxmemory-policy
      #   value: allkeys-lru

    # Optional: Snapshot configuration
    snapshotRetentionLimit: 7
    snapshotWindow: "03:00-05:00"

    # Optional: Maintenance window
    maintenanceWindow: "sun:05:00-sun:06:00"

    # Optional: Tags
    tags:
      Environment: production
      ManagedBy: crossplane
      Application: helicone-ai-gateway

    # Crossplane provider configuration reference
    providerConfigRef: aws-provider

    # Multi-region configuration
    multiRegion:
      enabled: false
      regions:
        []
        # - name: us-east-1
        #   nodeType: db.r7g.large  # Optional: Override global nodeType
        #   numShards: 1            # Optional: Override global numShards
        #   numReplicasPerShard: 1  # Optional: Override global numReplicasPerShard
        #   subnetIds:
        #     - subnet-12345678
        #     - subnet-87654321
        #   securityGroupIds:       # Optional: Override global securityGroupIds
        #     - sg-12345678
        #   kmsKeyId: "arn:aws:kms:us-east-1:account:key/..."  # Optional: Override global KMS key
        #   providerConfigRef: aws-provider-us-east-1  # Optional: Override provider config
        # - name: us-west-2
        #   subnetIds:
        #     - subnet-abcdef12
        #     - subnet-fedcba21
        #   kmsKeyId: "arn:aws:kms:us-west-2:account:key/..."
        # - name: eu-west-1
        #   subnetIds:
        #     - subnet-11111111
        #     - subnet-22222222

      # Global replication group configuration (optional)
      globalReplicationGroup:
        suffix: global
        automaticFailoverEnabled: true
        # cacheNodeType: cache.r7g.large  # Optional: Override node type for global replication
        # engineVersion: "7.0"            # Optional: Specify engine version
