{{- if .Values.helicone.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web.name" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    {{- include "helicone.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.helicone.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "helicone.web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helicone.web.selectorLabels" . | nindent 8 }}
    spec:
      {{- if or (and .Values.helicone.cloudSqlProxy.enabled .Values.helicone.cloudSqlProxy.useWorkloadIdentity) (and .Values.helicone.s3 .Values.helicone.s3.serviceAccount .Values.helicone.s3.serviceAccount.enabled) }}
      serviceAccountName: {{ include "web.name" . }}
      {{- end }}
      initContainers:
        {{- if .Values.helicone.cloudSqlProxy.enabled }}
        - name: cloud-sql-proxy
          image: {{ include "helicone.cloudSqlProxy.image" . }}
          imagePullPolicy: {{ .Values.helicone.cloudSqlProxy.image.pullPolicy }}
          args: {{- include "helicone.cloudSqlProxy.args" . | nindent 12 }}
          ports:
            - name: sql-proxy
              containerPort: {{ include "helicone.cloudSqlProxy.port" . }}
              protocol: TCP
          {{- if not .Values.helicone.cloudSqlProxy.useWorkloadIdentity }}
          volumeMounts:
            - name: cloudsql-key
              mountPath: /secrets/cloudsql
              readOnly: true
          {{- end }}
          env:
            - name: CSQL_PROXY_HEALTH_CHECK
              value: "true"
            - name: CSQL_PROXY_HTTP_PORT
              value: "9801"
            - name: CSQL_PROXY_HTTP_ADDRESS
              value: 0.0.0.0
          restartPolicy: Always
          {{- with .Values.helicone.cloudSqlProxy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          startupProbe:
            httpGet:
              path: /startup
              port: 9801
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
        {{- end }}
        - name: wait-for-jawn
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for Jawn to be ready..."
              until curl -sSf http://{{ include "jawn.name" . }}:{{ .Values.helicone.jawn.service.port }}/healthcheck; do
                echo "Jawn is not ready yet. Waiting..."
                sleep 2
              done
              echo "Jawn is ready!"
      containers:
        - name: web
          image: "{{ .Values.helicone.web.image.repository }}:{{ .Values.helicone.web.image.tag }}"
          imagePullPolicy: {{ .Values.helicone.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.helicone.web.service.port }}
              protocol: TCP
          env:
            {{- include "helicone.web.env" . | nindent 12 }}
            {{- with .Values.helicone.web.extraEnvVars }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.helicone.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          startupProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 4
      {{- if and .Values.helicone.cloudSqlProxy.enabled (not .Values.helicone.cloudSqlProxy.useWorkloadIdentity) }}
      volumes:
        - name: cloudsql-key
          secret:
            secretName: {{ .Values.helicone.cloudSqlProxy.serviceAccountSecretName }}
            items:
              - key: {{ .Values.helicone.cloudSqlProxy.serviceAccountSecretKey }}
                path: key.json
      {{- end }}
{{- end }}
