{{- if and .Values.helicone.web.enabled .Values.helicone.web.cloudSqlProxy.enabled .Values.helicone.web.cloudSqlProxy.useWorkloadIdentity }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "web.name" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    {{- include "helicone.annotations" . | nindent 4 }}
    {{- if .Values.helicone.web.cloudSqlProxy.workloadIdentityAnnotation }}
    iam.gke.io/gcp-service-account: {{ .Values.helicone.web.cloudSqlProxy.workloadIdentityAnnotation }}
    {{- end }}
{{- end }} 