{{- if or (and .Values.helicone.web.enabled .Values.helicone.web.cloudSqlProxy.enabled .Values.helicone.web.cloudSqlProxy.useWorkloadIdentity) (and .Values.helicone.s3 .Values.helicone.s3.serviceAccount .Values.helicone.s3.serviceAccount.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "web.name" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    {{- include "helicone.annotations" . | nindent 4 }}
    {{- if and .Values.helicone.web.cloudSqlProxy.enabled .Values.helicone.web.cloudSqlProxy.useWorkloadIdentity .Values.helicone.web.cloudSqlProxy.workloadIdentityAnnotation }}
    iam.gke.io/gcp-service-account: {{ .Values.helicone.web.cloudSqlProxy.workloadIdentityAnnotation }}
    {{- end }}
    {{- if and .Values.helicone.s3 .Values.helicone.s3.serviceAccount .Values.helicone.s3.serviceAccount.enabled }}
    eks.amazonaws.com/role-arn: {{ .Values.helicone.s3.serviceAccount.roleArn | quote }}
    {{- end }}
{{- end }} 