{{- if .Values.helicone.cloudnativepg.enabled }}
{{- /*
CloudNativePG PostgreSQL Cluster Configuration

CRITICAL: Image Requirements
============================
CloudNativePG REQUIRES specific PostgreSQL images that include the CNPG manager binary.
Using standard PostgreSQL images (bitnami/postgresql, postgres:latest, etc.) will cause:
- "Instance is still down, will retry in 1 second" loops
- "Error while getting streaming replication secret" errors
- Bootstrap controller failures

ALWAYS use images from: ghcr.io/cloudnative-pg/postgresql

To change PostgreSQL version, update values.yaml:
  helicone.cloudnativepg.cluster.image.tag

Supported versions: https://github.com/cloudnative-pg/postgres-containers
*/ -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.helicone.cloudnativepg.cluster.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,RespectIgnoreDifferences=true,Validate=false,Replace=true,ServerSideApply=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/hook: Skip
spec:
  instances: {{ .Values.helicone.cloudnativepg.cluster.instances }}
  
  # PostgreSQL image configuration
  # IMPORTANT: Must use CloudNativePG-compatible images (ghcr.io/cloudnative-pg/postgresql)
  # Standard PostgreSQL images will cause the cluster to fail with "Instance is still down" errors
  imageName: {{ .Values.helicone.cloudnativepg.cluster.image.name }}:{{ .Values.helicone.cloudnativepg.cluster.image.tag }}
  
  postgresql:
    parameters:
      {{- range $key, $value := .Values.helicone.cloudnativepg.cluster.postgresql.parameters }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  
  bootstrap:
    initdb:
      database: {{ .Values.helicone.cloudnativepg.cluster.bootstrap.initdb.database }}
      owner: {{ .Values.helicone.cloudnativepg.cluster.bootstrap.initdb.owner }}
      secret:
        name: {{ .Values.helicone.cloudnativepg.cluster.bootstrap.initdb.secret.name }}
      {{- if .Values.helicone.cloudnativepg.cluster.bootstrap.initdb.postInitSQL }}
      postInitSQL:
        - {{ printf "ALTER USER helicone PASSWORD '%s';" .Values.helicone.config.heliconePassword | quote }}
        {{- range .Values.helicone.cloudnativepg.cluster.bootstrap.initdb.postInitSQL }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
  
  storage:
    size: {{ .Values.helicone.cloudnativepg.cluster.storage.size }}
    {{- if .Values.helicone.cloudnativepg.cluster.storage.storageClass }}
    storageClass: {{ .Values.helicone.cloudnativepg.cluster.storage.storageClass }}
    {{- end }}
  
  {{- if .Values.helicone.cloudnativepg.cluster.monitoring.enabled }}
  monitoring:
    enablePodMonitor: {{ .Values.helicone.cloudnativepg.cluster.monitoring.enabled }}
  {{- end }}
  
  {{- if .Values.helicone.cloudnativepg.cluster.backup.enabled }}
  backup:
    retentionPolicy: {{ .Values.helicone.cloudnativepg.cluster.backup.retentionPolicy }}
    barmanObjectStore:
      destinationPath: s3://your-backup-bucket/postgres-backups
      s3Credentials:
        accessKeyId:
          name: backup-storage-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backup-storage-creds
          key: SECRET_ACCESS_KEY
      wal:
        retention: {{ .Values.helicone.cloudnativepg.cluster.backup.retentionPolicy }}
      data:
        retention: {{ .Values.helicone.cloudnativepg.cluster.backup.retentionPolicy }}
  {{- end }}
  
  resources:
    requests:
      memory: {{ .Values.helicone.cloudnativepg.cluster.resources.requests.memory }}
      cpu: {{ .Values.helicone.cloudnativepg.cluster.resources.requests.cpu }}
    limits:
      memory: {{ .Values.helicone.cloudnativepg.cluster.resources.limits.memory }}
      cpu: {{ .Values.helicone.cloudnativepg.cluster.resources.limits.cpu }}
{{- end }}