{{- if .Values.helicone.cloudnativepg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.helicone.cloudnativepg.cluster.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,RespectIgnoreDifferences=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  instances: {{ .Values.helicone.cloudnativepg.cluster.instances }}
  
  # Use the current Bitnami PostgreSQL image to prevent restarts
  imageName: docker.io/bitnami/postgresql:17.5.0-debian-12-r20
  
  postgresql:
    parameters:
      {{- range $key, $value := .Values.helicone.cloudnativepg.cluster.postgresql.parameters }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  
  bootstrap:
    initdb:
      database: {{ .Values.helicone.cloudnativepg.cluster.bootstrap.initdb.database }}
      owner: {{ .Values.helicone.cloudnativepg.cluster.bootstrap.initdb.owner }}
      secret:
        name: {{ .Values.helicone.cloudnativepg.cluster.bootstrap.initdb.secret.name }}
      {{- if .Values.helicone.cloudnativepg.cluster.bootstrap.initdb.postInitSQL }}
      postInitSQL:
        - {{ printf "ALTER USER helicone PASSWORD '%s';" .Values.helicone.config.heliconePassword | quote }}
        {{- range .Values.helicone.cloudnativepg.cluster.bootstrap.initdb.postInitSQL }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
  
  storage:
    size: {{ .Values.helicone.cloudnativepg.cluster.storage.size }}
    {{- if .Values.helicone.cloudnativepg.cluster.storage.storageClass }}
    storageClass: {{ .Values.helicone.cloudnativepg.cluster.storage.storageClass }}
    {{- end }}
  
  {{- if .Values.helicone.cloudnativepg.cluster.monitoring.enabled }}
  monitoring:
    enablePodMonitor: {{ .Values.helicone.cloudnativepg.cluster.monitoring.enabled }}
  {{- end }}
  
  {{- if .Values.helicone.cloudnativepg.cluster.backup.enabled }}
  backup:
    retentionPolicy: {{ .Values.helicone.cloudnativepg.cluster.backup.retentionPolicy }}
    barmanObjectStore:
      destinationPath: s3://your-backup-bucket/postgres-backups
      s3Credentials:
        accessKeyId:
          name: backup-storage-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backup-storage-creds
          key: SECRET_ACCESS_KEY
      wal:
        retention: {{ .Values.helicone.cloudnativepg.cluster.backup.retentionPolicy }}
      data:
        retention: {{ .Values.helicone.cloudnativepg.cluster.backup.retentionPolicy }}
  {{- end }}
  
  resources:
    requests:
      memory: {{ .Values.helicone.cloudnativepg.cluster.resources.requests.memory }}
      cpu: {{ .Values.helicone.cloudnativepg.cluster.resources.requests.cpu }}
    limits:
      memory: {{ .Values.helicone.cloudnativepg.cluster.resources.limits.memory }}
      cpu: {{ .Values.helicone.cloudnativepg.cluster.resources.limits.cpu }}
{{- end }}