{{- if .Values.loki.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helicone.fullname" . }}-loki-config
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
    component: loki
data:
  local-config.yaml: |
    {{- toYaml .Values.loki.config | nindent 4 }}
{{- end }} 