{{- if .Values.helicone.clickhouse.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "clickhouse.name" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    {{- include "helicone.annotations" . | nindent 4 }}
spec:
  serviceName: {{ include "clickhouse.name" . }}
  replicas: {{ .Values.helicone.clickhouse.replicaCount }}
  selector:
    matchLabels:
      {{- include "clickhouse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "clickhouse.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "clickhouse.name" . }}
          image: "{{ .Values.helicone.clickhouse.image.repository }}:{{ .Values.helicone.clickhouse.image.tag }}"
          imagePullPolicy: {{ .Values.helicone.clickhouse.image.pullPolicy }}
          env:
            {{- include "helicone.env.clickhouseUser" . | nindent 12 }}
            {{- with .Values.helicone.clickhouse.extraEnvVars }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.helicone.clickhouse.service.port }}
              protocol: TCP
          volumeMounts:
            - name: db
              mountPath: /var/lib/clickhouse
          {{- with .Values.helicone.clickhouse.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 10
            failureThreshold: 10
  volumeClaimTemplates:
    - metadata:
        name: db
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.helicone.clickhouse.persistence.size }}
        storageClassName: {{ .Values.helicone.clickhouse.persistence.storageClass }}

{{- end }}