{{- if .Values.awsGatewayController.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.awsGatewayController.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  {{- with .Values.awsGatewayController.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helicone.fullname" . }}-gateway-controller
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
      - nodes
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gateways
      - gatewayclasses
      - httproutes
      - tcproutes
      - tlsroutes
      - referencegrants
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gateways/status
      - gatewayclasses/status
      - httproutes/status
      - tcproutes/status
      - tlsroutes/status
    verbs:
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helicone.fullname" . }}-gateway-controller
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "helicone.fullname" . }}-gateway-controller
subjects:
  - kind: ServiceAccount
    name: {{ .Values.awsGatewayController.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helicone.fullname" . }}-gateway-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "helicone.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway-controller
  template:
    metadata:
      labels:
        {{- include "helicone.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gateway-controller
    spec:
      serviceAccountName: {{ .Values.awsGatewayController.serviceAccount.name }}
      containers:
      - name: controller
        image: public.ecr.aws/aws-application-networking-k8s/aws-gateway-controller:{{ .Values.awsGatewayController.version }}
        args:
          - --aws-region={{ .Values.awsGatewayController.region }}
          - --aws-vpc-id={{ .Values.awsGatewayController.vpcId }}
          - --log-level=info
          - --enable-service-controller=true
          - --enable-route-controller=true
        env:
        - name: AWS_REGION
          value: {{ .Values.awsGatewayController.region }}
        - name: AWS_VPC_ID
          value: {{ .Values.awsGatewayController.vpcId | quote }}
        {{- if .Values.awsGatewayController.accountId }}
        - name: AWS_ACCOUNT_ID
          value: {{ .Values.awsGatewayController.accountId | quote }}
        {{- end }}
        ports:
        - name: webhook
          containerPort: 9443
          protocol: TCP
        - name: metrics
          containerPort: 8080
          protocol: TCP
        - name: health
          containerPort: 8081
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.awsGatewayController.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helicone.fullname" . }}-gateway-controller-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway-controller
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: webhook
  selector:
    {{- include "helicone.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway-controller
{{- end }}