{{- if .Values.awsGatewayController.enabled }}
---
# GatewayClass for Application Load Balancer (ALB)
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: amazon-vpc-lattice
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
spec:
  controllerName: application-networking.k8s.aws/gateway-api-controller
  parametersRef:
    group: application-networking.k8s.aws
    kind: VpcAssociationPolicy
    name: default-vpc-association
    namespace: {{ .Release.Namespace }}
---
# VPC Association Policy for ALB
apiVersion: application-networking.k8s.aws/v1beta1
kind: VpcAssociationPolicy
metadata:
  name: default-vpc-association
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
spec:
  securityGroupIds: []  # Optional: specify security groups
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: "*"  # Apply to all gateways using this policy
---
# GatewayClass for Network Load Balancer (NLB)
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: aws-gateway-controller-nlb
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
spec:
  controllerName: networking.k8s.aws/gateway-api-controller
  parametersRef:
    group: ""
    kind: ConfigMap
    name: {{ include "helicone.fullname" . }}-nlb-params
    namespace: {{ .Release.Namespace }}
---
# ConfigMap for NLB parameters
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helicone.fullname" . }}-nlb-params
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
data:
  aws-load-balancer-type: "nlb"
  aws-load-balancer-scheme: "internet-facing"
  aws-load-balancer-backend-protocol: "tcp"
  aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  aws-load-balancer-target-type: "ip"
{{- end }}