{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "helicone.fullname" . }}-nlb-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: {{ .Values.gateway.allowedRoutes.namespaces.from | default "All" }}
        {{- if .Values.gateway.allowedRoutes.namespaces.selector }}
        selector:
          {{- toYaml .Values.gateway.allowedRoutes.namespaces.selector | nindent 10 }}
        {{- end }}
  - name: https
    protocol: HTTPS
    port: 443
    {{- if .Values.gateway.tls.mode }}
    tls:
      mode: {{ .Values.gateway.tls.mode }}
      {{- if eq .Values.gateway.tls.mode "Terminate" }}
      certificateRefs:
      {{- range .Values.gateway.tls.certificateRefs }}
      - name: {{ .name }}
        {{- if .namespace }}
        namespace: {{ .namespace }}
        {{- end }}
        {{- if .group }}
        group: {{ .group }}
        {{- end }}
        {{- if .kind }}
        kind: {{ .kind }}
        {{- end }}
      {{- end }}
      {{- end }}
    {{- end }}
    allowedRoutes:
      namespaces:
        from: {{ .Values.gateway.allowedRoutes.namespaces.from | default "All" }}
        {{- if .Values.gateway.allowedRoutes.namespaces.selector }}
        selector:
          {{- toYaml .Values.gateway.allowedRoutes.namespaces.selector | nindent 10 }}
        {{- end }}
  {{- if .Values.gateway.addresses }}
  addresses:
  {{- range .Values.gateway.addresses }}
  - type: {{ .type }}
    value: {{ .value }}
  {{- end }}
  {{- end }}
---
# Default HTTPRoute for cross-namespace ingress support
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "helicone.fullname" . }}-default-route
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ include "helicone.fullname" . }}-nlb-gateway
    namespace: {{ .Release.Namespace }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
        - name: X-Forwarded-Proto
          value: "https"
    backendRefs: []  # This will be empty as it's just a gateway for other namespaces
{{- end }}