{{- if .Values.jaeger.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helicone.name" . }}-jaeger
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
    component: jaeger
spec:
  type: {{ .Values.jaeger.service.type }}
  ports:
  {{- range $name, $port := .Values.jaeger.service.ports }}
  - name: {{ $name }}
    port: {{ $port.port }}
    targetPort: {{ $port.targetPort }}
    protocol: TCP
  {{- end }}
  selector:
    {{- include "helicone.selectorLabels" . | nindent 4 }}
    component: jaeger
---
# Additional service for collector endpoints
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
    component: jaeger
    service: jaeger-collector
spec:
  type: ClusterIP
  ports:
  - name: jaeger-grpc
    port: 14250
    targetPort: 14250
    protocol: TCP
  - name: jaeger-thrift
    port: 14268
    targetPort: 14268
    protocol: TCP
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: otlp-http
    port: 4318
    targetPort: 4318
    protocol: TCP
  - name: zipkin
    port: 9411
    targetPort: 9411
    protocol: TCP
  selector:
    {{- include "helicone.selectorLabels" . | nindent 4 }}
    component: jaeger
{{- end }} 