{{- if .Values.sealedSecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: {{ .Values.global.argocd.namespace | default "argocd" }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.16.1
    helm:
      values: |
        fullnameOverride: {{ .Values.sealedSecrets.fullnameOverride | quote }}
        
        image:
          tag: {{ .Values.sealedSecrets.image.tag | quote }}
        
        resources:
          {{- toYaml .Values.sealedSecrets.resources | nindent 10 }}
        
        commandArgs:
          - --key-renew-period={{ .Values.sealedSecrets.keyRenewPeriod }}
        
        # Security context for OpenShift/Kubernetes
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          fsGroup: 65534
          seccompProfile:
            type: RuntimeDefault
        
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 65534
          fsGroup: 65534
          seccompProfile:
            type: RuntimeDefault
        
        # Service account
        serviceAccount:
          create: true
          name: sealed-secrets
        
        # RBAC
        rbac:
          create: true
          
        # Service configuration
        service:
          type: ClusterIP
          port: 8080
          
        # Pod disruption budget
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
          
        # Monitoring
        metrics:
          enabled: true
          serviceMonitor:
            enabled: false  # Enable if you have Prometheus Operator
            
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.sealedSecrets.namespace }}
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
  revisionHistoryLimit: 3
{{- end }} 