{{- if .Values.tempo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helicone.name" . }}-tempo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
    component: tempo
spec:
  type: {{ .Values.tempo.service.type }}
  ports:
  {{- range $name, $port := .Values.tempo.service.ports }}
  - name: {{ $name }}
    port: {{ $port.port }}
    targetPort: {{ $port.targetPort }}
    protocol: TCP
  {{- end }}
  - name: grpc
    port: 9095
    targetPort: 9095
    protocol: TCP
  selector:
    {{- include "helicone.selectorLabels" . | nindent 4 }}
    component: tempo
---
# Service for OTLP and tracing endpoints
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
    component: tempo
    service: tempo-collector
spec:
  type: ClusterIP
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: tempo-http
    port: 3200
    targetPort: 3200
    protocol: TCP
  selector:
    {{- include "helicone.selectorLabels" . | nindent 4 }}
    component: tempo
{{- end }}